// * EMBEDDING DOMAIN MODULE - CONSTANTS
// ? Defines static tokens and task type mappings for vector generation.

const TASK_TYPES = {
  RETRIEVAL_DOCUMENT: "RETRIEVAL_DOCUMENT",
  RETRIEVAL_QUERY: "RETRIEVAL_QUERY",
  SEMANTIC_SIMILARITY: "SEMANTIC_SIMILARITY",
  CLASSIFICATION: "CLASSIFICATION",
  CLUSTERING: "CLUSTERING",
};

module.exports = {
  TASK_TYPES,
};
